---
# This is Ubuntu specific tasks

- name: Install Ubuntu package dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - npm
    - nodejs
    - python34
    - python34-setuptools
    - python34-devel
    - httpd
    - httpd-devel
    - httpd-tools
    - libtool
    - libcurl3
    - libcurl3-devel
    - pcre
    - pcre-devel

- name: Install pip under python3
  command: /usr/bin/python3 easy_install.py pip chdir=/usr/lib/python3.4/site-packages/

- name: install virtualenv
  pip:
    name: virtualenv
    state: latest
    executable: pip3
