---
# This is CentOS specific tasks

- name: Install CentOS package dependencies
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - npm
    - nodejs
    - python34
    - python34-setuptools
    - python34-devel
    - python34-pip
    - httpd
    - httpd-devel
    - httpd-tools
    - libtool
    - libcurl
    - libcurl-devel
    - pcre
    - pcre-devel
    - mod_auth_cas

#- name: Install pip under python3
#  command: /usr/bin/python3 easy_install.py pip chdir=/usr/lib/python3.4/site-packages/

- name: install virtualenv
  pip:
    name: virtualenv
    state: latest
    executable: pip3
