---
# This task file requires kubernetes.core. Install with:
# ansible-galaxy collection install kubernetes.core

- name: FAIL; check github auth
  fail:
    msg: "auth classs is set to dummy but DUMMY_PASS is not defined"
  when: AUTH_CLASS == "github" and (OAUTH2_CLIENT_ID is not defined or OAUTH2_CLIENT_SECRET is not defined)

- name: FAIL; check dummy pass
  fail:
    msg: "auth classs is set to dummy but DUMMY_PASS is not defined"
  when: AUTH_CLASS == "dummy" and DUMMY_PASS is not defined

- name: SHELL; install k3s
  shell:
    cmd: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --no-deploy traefik" sh

- name: SHELL; install helm
  shell:
    cmd: curl https://raw.githubusercontent.com/helm/helm/HEAD/scripts/get-helm-3 | bash

- name: TEMPLATE; config.yaml
  template:
    src: config.yaml.j2
    dest: config.yaml

- name: SHELL; Add jupyterhub chart repo
  shell:
    cmd: helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/ ; helm repo update

- name: SHELL; Upgrade helm chart
  shell:
    cmd: helm --kubeconfig /etc/rancher/k3s/k3s.yaml upgrade --cleanup-on-fail --install jupyterhelm jupyterhub/jupyterhub --namespace {{ namespace }} --create-namespace --values config.yaml --timeout 10m
  async: 600
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: SHELL; set namespace context
  shell:
    cmd: kubectl config set-context $(kubectl config current-context) --namespace {{ namespace }}
