---
# This task file requires kubernetes.core. Install with:
# ansible-galaxy collection install kubernetes.core

- name: FAIL; check oauth2 variables when an oauth2 provider is selected
  fail:
    msg: "Auth class = {{ JH_AUTH_CLASS }} but one of JH_OAUTH2_CLIENT_ID, JH_OAUTH2_CLIENT_SECRET, or JH_OAUTH2_CALLBACK_URL is not defined "
  when: JH_AUTH_CLASS == "github" and (JH_OAUTH2_CLIENT_ID is not defined or JH_OAUTH2_CLIENT_ID == "" or JH_OAUTH2_CLIENT_SECRET is not defined or JH_OAUTH2_CLIENT_SECRET == "" or JH_OAUTH2_CALLBACK_URL is not defined or JH_OAUTH2_CALLBACK_URL is not defined == "")

- name: FAIL; check dummy password
  fail:
    msg: "JH_AUTH_CLASS is set to dummy but JH_DUMMY_PASS is not defined"
  when: JH_AUTH_CLASS == "dummy" and JH_DUMMY_PASS is not defined

- name: SHELL; locate kubectl binary
  shell: command -v kubectl
  register: kubectl_found
  ignore_errors: yes

- name: FAIL; check if kubectl binary is not found
  fail:
    msg: "This role requires kubectl"
  when: kubectl_found is failed

- name: TEMPLATE; config.yaml
  template:
    src: config.yaml.j2
    dest: config.yaml

- name: SHELL; Add jupyterhub chart repo
  shell:
    cmd: helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/ ; helm repo update

- name: SHELL; Upgrade helm chart
  shell:
    cmd: helm --kubeconfig /etc/rancher/k3s/k3s.yaml upgrade --cleanup-on-fail --install jupyterhelm jupyterhub/jupyterhub --namespace {{ namespace }} --create-namespace --values config.yaml --timeout 10m
  async: 600
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: SHELL; set namespace context
  shell:
    cmd: kubectl config set-context $(kubectl config current-context) --namespace {{ namespace }}
