---
# This is Ubuntu specific tasks to configure apache
- name: Enable apache modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - auth_cas
    - proxy_http
    - rewrite
    - headers
    - proxy_wstunnel
  notify: restart apache2

- name: stat the default site
  stat: path=/etc/apache2/sites-enabled/000-default.conf
  register: default_site

- name: disable default site
  command: a2dissite 000-default
  when: default_site.stat.exists == True
  notify: restart apache2

- name: install the jupyterhub.conf
  copy:
    src: jupyterhub.conf
    dest: /etc/apache2/sites-available/jupyterhub.conf
    owner: root
    group: root
    mode: 0644
  notify: restart apache2

- name: enable jupyterhub config file
  command: a2ensite jupyterhub
  notify: restart apache2
